import { useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { PageHeader } from "@/components/app-chrome";
import { getWorkspace } from "@/lib/workspace.functions";
import { streamImage, brandImagePrompt } from "@/lib/stream-image";
import { Sparkles, Download, Loader2 } from "lucide-react";
import { toast } from "sonner";

export const Route = createFileRoute("/app/images")({ loader: () => getWorkspace(), component: Images });
const FORMATS = ["Facebook", "Instagram", "Story", "Banner", "Szórólap", "Hirdetés"];
function Images() {
  const data = Route.useLoaderData(); const brand = data.activeBrand;
  const [topic, setTopic] = useState(""); const [format, setFormat] = useState("Instagram"); const [images, setImages] = useState<{ src: string; final: boolean; format: string }[]>([]); const [busy, setBusy] = useState(false);
  if (!brand) return <Card className="rounded-3xl p-10 text-center"><Sparkles className="mx-auto h-8 w-8 text-brand" /><div className="mt-3 text-lg font-semibold">Még nincs aktív márkád</div><p className="mx-auto mt-1 max-w-md text-sm text-muted-foreground">Az AI képgeneráláshoz előbb ments márkát és Brand Voice-ot.</p><Link to="/app/brand"><Button className="mt-4 rounded-full">Márka létrehozása</Button></Link></Card>;
  const activeBrand = brand;
  async function generate() { if (busy || topic.trim().length < 2) return; setBusy(true); const index = images.length; setImages((current) => [...current, { src: "", final: false, format }]); try { await streamImage(brandImagePrompt({ topic, brand: activeBrand.name, industry: activeBrand.industry, businessType: activeBrand.profile.businessType, tone: activeBrand.profile.tone, colors: activeBrand.profile.colors, format }), (dataUrl, isFinal) => setImages((current) => current.map((item, i) => i === index ? { ...item, src: dataUrl, final: isFinal } : item)), { brandId: activeBrand.id, format }); } catch (cause) { setImages((current) => current.filter((_, i) => i !== index)); toast.error(cause instanceof Error ? cause.message : "Nem sikerült a képgenerálás."); } finally { setBusy(false); } }
  async function saveToMedia(src: string, name: string) { try { const response = await fetch(src); const blob = await response.blob(); const form = new FormData(); form.append("file", blob, name + ".png"); form.append("brandId", activeBrand.id); form.append("source", "ai"); form.append("altText", name); const upload = await fetch("/api/media", { method: "POST", body: form }); if (!upload.ok) throw new Error("A média mentése sikertelen."); toast.success("A kép bekerült a Médiatárba."); } catch (cause) { toast.error(cause instanceof Error ? cause.message : "Nem sikerült menteni a képet."); } }
  return <div className="space-y-6"><PageHeader title="Kép készítése" sub="Márkahű vizuálok posztokhoz, Story-khoz és hirdetésekhez." /><Card className="rounded-3xl p-6"><div className="grid gap-3 md:grid-cols-[minmax(0,1fr)_auto]"><Input className="h-12 rounded-2xl text-base" value={topic} onChange={(event) => setTopic(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void generate(); }} placeholder="Mit ábrázoljon a kép?" /><Button className="h-12 rounded-2xl px-6" disabled={busy || topic.trim().length < 2} onClick={() => void generate()}>{busy ? <Loader2 className="mr-1 h-4 w-4 animate-spin" /> : <Sparkles className="mr-1 h-4 w-4" />}{busy ? "Generálás…" : "Generálás"}</Button></div><div className="mt-4 flex flex-wrap gap-2">{FORMATS.map((item) => <button key={item} onClick={() => setFormat(item)}><Badge variant={format === item ? "default" : "outline"} className="rounded-full">{item}</Badge></button>)}</div><div className="mt-3 flex flex-wrap items-center gap-2 text-xs text-muted-foreground">Márka: {brand.name} · Hangnem: {brand.profile.tone}{brand.profile.colors.map((color) => <span key={color} className="h-4 w-4 rounded-full border" style={{ background: color }} />)}</div></Card>{images.length === 0 ? <Card className="rounded-3xl p-10 text-center"><Sparkles className="mx-auto h-8 w-8 text-brand" /><div className="mt-3 text-lg font-semibold">Generálj éles AI képet a márkádhoz</div><p className="mx-auto mt-1 max-w-md text-sm text-muted-foreground">A kérés az aktív márka vizuális identitását és Brand Voice-át használja.</p></Card> : <div className="grid gap-4 md:grid-cols-4">{images.map((img, i) => <Card key={i} className="overflow-hidden rounded-3xl">{img.src ? <img src={img.src} alt={brand.name + " AI vizuál – " + img.format} className={"aspect-square w-full object-cover transition-[filter] duration-300 " + (img.final ? "blur-0" : "blur-2xl")} /> : <div className="flex aspect-square items-center justify-center bg-secondary"><Loader2 className="h-6 w-6 animate-spin text-muted-foreground" /></div>}<div className="flex items-center justify-between p-3"><div className="text-xs"><div className="font-medium">Variáció {i + 1}</div><div className="text-muted-foreground">{img.format}</div></div><div className="flex gap-1"><Button size="icon" variant="ghost" disabled={!img.final} onClick={() => { const link = document.createElement("a"); link.href = img.src; link.download = brand.name + "-" + img.format + "-" + (i + 1) + ".png"; link.click(); }}><Download className="h-4 w-4" /></Button><Button size="sm" variant="outline" className="rounded-full" disabled={!img.final} onClick={() => void saveToMedia(img.src, brand.name + "-" + img.format + "-" + (i + 1))}>Médiatárba mentés</Button></div></div></Card>)}</div>}</div>;
}
