/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiMediaRouteImport } from './routes/api/media'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppBrandRouteImport } from './routes/app.brand'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppCampaignsRouteImport } from './routes/app.campaigns'
import { Route as AppChannelsRouteImport } from './routes/app.channels'
import { Route as AppIdeasRouteImport } from './routes/app.ideas'
import { Route as AppImagesRouteImport } from './routes/app.images'
import { Route as AppMediaRouteImport } from './routes/app.media'
import { Route as AppPlannerRouteImport } from './routes/app.planner'
import { Route as AppPostsRouteImport } from './routes/app.posts'
import { Route as AppRecommendationsRouteImport } from './routes/app.recommendations'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSubscriptionRouteImport } from './routes/app.subscription'
import { Route as ApiChannelsOauthCallbackRouteImport } from './routes/api/channels/oauth-callback'
import { Route as ApiMediaIdRouteImport } from './routes/api/media.$id'
import { Route as AppCampaignsIdRouteImport } from './routes/app.campaigns.$id'
import { Route as AppContentTypeRouteImport } from './routes/app.content.$type'
import { Route as AppPostsIdRouteImport } from './routes/app.posts.$id'
import { Route as ApiChannelsOauthProviderRouteImport } from './routes/api/channels/oauth.$provider'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandRoute = AppBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsRoute = AppChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AppRoute,
} as any)
const AppIdeasRoute = AppIdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => AppRoute,
} as any)
const AppImagesRoute = AppImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => AppRoute,
} as any)
const AppMediaRoute = AppMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AppRoute,
} as any)
const AppPlannerRoute = AppPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AppRoute,
} as any)
const AppPostsRoute = AppPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AppRoute,
} as any)
const AppRecommendationsRoute = AppRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const ApiChannelsOauthCallbackRoute =
  ApiChannelsOauthCallbackRouteImport.update({
    id: '/api/channels/oauth-callback',
    path: '/api/channels/oauth-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMediaIdRoute = ApiMediaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMediaRoute,
} as any)
const AppCampaignsIdRoute = AppCampaignsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCampaignsRoute,
} as any)
const AppContentTypeRoute = AppContentTypeRouteImport.update({
  id: '/content/$type',
  path: '/content/$type',
  getParentRoute: () => AppRoute,
} as any)
const AppPostsIdRoute = AppPostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPostsRoute,
} as any)
const ApiChannelsOauthProviderRoute =
  ApiChannelsOauthProviderRouteImport.update({
    id: '/api/channels/oauth/$provider',
    path: '/api/channels/oauth/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/media': typeof ApiMediaRouteWithChildren
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/brand': typeof AppBrandRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/campaigns': typeof AppCampaignsRouteWithChildren
  '/app/channels': typeof AppChannelsRoute
  '/app/ideas': typeof AppIdeasRoute
  '/app/images': typeof AppImagesRoute
  '/app/media': typeof AppMediaRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/posts': typeof AppPostsRouteWithChildren
  '/app/recommendations': typeof AppRecommendationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/': typeof AppIndexRoute
  '/api/channels/oauth-callback': typeof ApiChannelsOauthCallbackRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/app/campaigns/$id': typeof AppCampaignsIdRoute
  '/app/content/$type': typeof AppContentTypeRoute
  '/app/posts/$id': typeof AppPostsIdRoute
  '/api/channels/oauth/$provider': typeof ApiChannelsOauthProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/media': typeof ApiMediaRouteWithChildren
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/brand': typeof AppBrandRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/campaigns': typeof AppCampaignsRouteWithChildren
  '/app/channels': typeof AppChannelsRoute
  '/app/ideas': typeof AppIdeasRoute
  '/app/images': typeof AppImagesRoute
  '/app/media': typeof AppMediaRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/posts': typeof AppPostsRouteWithChildren
  '/app/recommendations': typeof AppRecommendationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app': typeof AppIndexRoute
  '/api/channels/oauth-callback': typeof ApiChannelsOauthCallbackRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/app/campaigns/$id': typeof AppCampaignsIdRoute
  '/app/content/$type': typeof AppContentTypeRoute
  '/app/posts/$id': typeof AppPostsIdRoute
  '/api/channels/oauth/$provider': typeof ApiChannelsOauthProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/media': typeof ApiMediaRouteWithChildren
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/brand': typeof AppBrandRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/campaigns': typeof AppCampaignsRouteWithChildren
  '/app/channels': typeof AppChannelsRoute
  '/app/ideas': typeof AppIdeasRoute
  '/app/images': typeof AppImagesRoute
  '/app/media': typeof AppMediaRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/posts': typeof AppPostsRouteWithChildren
  '/app/recommendations': typeof AppRecommendationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/': typeof AppIndexRoute
  '/api/channels/oauth-callback': typeof ApiChannelsOauthCallbackRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/app/campaigns/$id': typeof AppCampaignsIdRoute
  '/app/content/$type': typeof AppContentTypeRoute
  '/app/posts/$id': typeof AppPostsIdRoute
  '/api/channels/oauth/$provider': typeof ApiChannelsOauthProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/contact'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/api/generate-image'
    | '/api/media'
    | '/app/admin'
    | '/app/analytics'
    | '/app/brand'
    | '/app/calendar'
    | '/app/campaigns'
    | '/app/channels'
    | '/app/ideas'
    | '/app/images'
    | '/app/media'
    | '/app/planner'
    | '/app/posts'
    | '/app/recommendations'
    | '/app/settings'
    | '/app/subscription'
    | '/app/'
    | '/api/channels/oauth-callback'
    | '/api/media/$id'
    | '/app/campaigns/$id'
    | '/app/content/$type'
    | '/app/posts/$id'
    | '/api/channels/oauth/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/api/generate-image'
    | '/api/media'
    | '/app/admin'
    | '/app/analytics'
    | '/app/brand'
    | '/app/calendar'
    | '/app/campaigns'
    | '/app/channels'
    | '/app/ideas'
    | '/app/images'
    | '/app/media'
    | '/app/planner'
    | '/app/posts'
    | '/app/recommendations'
    | '/app/settings'
    | '/app/subscription'
    | '/app'
    | '/api/channels/oauth-callback'
    | '/api/media/$id'
    | '/app/campaigns/$id'
    | '/app/content/$type'
    | '/app/posts/$id'
    | '/api/channels/oauth/$provider'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/contact'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/api/generate-image'
    | '/api/media'
    | '/app/admin'
    | '/app/analytics'
    | '/app/brand'
    | '/app/calendar'
    | '/app/campaigns'
    | '/app/channels'
    | '/app/ideas'
    | '/app/images'
    | '/app/media'
    | '/app/planner'
    | '/app/posts'
    | '/app/recommendations'
    | '/app/settings'
    | '/app/subscription'
    | '/app/'
    | '/api/channels/oauth-callback'
    | '/api/media/$id'
    | '/app/campaigns/$id'
    | '/app/content/$type'
    | '/app/posts/$id'
    | '/api/channels/oauth/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiMediaRoute: typeof ApiMediaRouteWithChildren
  ApiChannelsOauthCallbackRoute: typeof ApiChannelsOauthCallbackRoute
  ApiChannelsOauthProviderRoute: typeof ApiChannelsOauthProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/brand': {
      id: '/app/brand'
      path: '/brand'
      fullPath: '/app/brand'
      preLoaderRoute: typeof AppBrandRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campaigns': {
      id: '/app/campaigns'
      path: '/campaigns'
      fullPath: '/app/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/channels': {
      id: '/app/channels'
      path: '/channels'
      fullPath: '/app/channels'
      preLoaderRoute: typeof AppChannelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ideas': {
      id: '/app/ideas'
      path: '/ideas'
      fullPath: '/app/ideas'
      preLoaderRoute: typeof AppIdeasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/images': {
      id: '/app/images'
      path: '/images'
      fullPath: '/app/images'
      preLoaderRoute: typeof AppImagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/media': {
      id: '/app/media'
      path: '/media'
      fullPath: '/app/media'
      preLoaderRoute: typeof AppMediaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/planner': {
      id: '/app/planner'
      path: '/planner'
      fullPath: '/app/planner'
      preLoaderRoute: typeof AppPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/posts': {
      id: '/app/posts'
      path: '/posts'
      fullPath: '/app/posts'
      preLoaderRoute: typeof AppPostsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recommendations': {
      id: '/app/recommendations'
      path: '/recommendations'
      fullPath: '/app/recommendations'
      preLoaderRoute: typeof AppRecommendationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subscription': {
      id: '/app/subscription'
      path: '/subscription'
      fullPath: '/app/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/channels/oauth-callback': {
      id: '/api/channels/oauth-callback'
      path: '/api/channels/oauth-callback'
      fullPath: '/api/channels/oauth-callback'
      preLoaderRoute: typeof ApiChannelsOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$id': {
      id: '/api/media/$id'
      path: '/$id'
      fullPath: '/api/media/$id'
      preLoaderRoute: typeof ApiMediaIdRouteImport
      parentRoute: typeof ApiMediaRoute
    }
    '/app/campaigns/$id': {
      id: '/app/campaigns/$id'
      path: '/$id'
      fullPath: '/app/campaigns/$id'
      preLoaderRoute: typeof AppCampaignsIdRouteImport
      parentRoute: typeof AppCampaignsRoute
    }
    '/app/content/$type': {
      id: '/app/content/$type'
      path: '/content/$type'
      fullPath: '/app/content/$type'
      preLoaderRoute: typeof AppContentTypeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/posts/$id': {
      id: '/app/posts/$id'
      path: '/$id'
      fullPath: '/app/posts/$id'
      preLoaderRoute: typeof AppPostsIdRouteImport
      parentRoute: typeof AppPostsRoute
    }
    '/api/channels/oauth/$provider': {
      id: '/api/channels/oauth/$provider'
      path: '/api/channels/oauth/$provider'
      fullPath: '/api/channels/oauth/$provider'
      preLoaderRoute: typeof ApiChannelsOauthProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppCampaignsRouteChildren {
  AppCampaignsIdRoute: typeof AppCampaignsIdRoute
}

const AppCampaignsRouteChildren: AppCampaignsRouteChildren = {
  AppCampaignsIdRoute: AppCampaignsIdRoute,
}

const AppCampaignsRouteWithChildren = AppCampaignsRoute._addFileChildren(
  AppCampaignsRouteChildren,
)

interface AppPostsRouteChildren {
  AppPostsIdRoute: typeof AppPostsIdRoute
}

const AppPostsRouteChildren: AppPostsRouteChildren = {
  AppPostsIdRoute: AppPostsIdRoute,
}

const AppPostsRouteWithChildren = AppPostsRoute._addFileChildren(
  AppPostsRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBrandRoute: typeof AppBrandRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCampaignsRoute: typeof AppCampaignsRouteWithChildren
  AppChannelsRoute: typeof AppChannelsRoute
  AppIdeasRoute: typeof AppIdeasRoute
  AppImagesRoute: typeof AppImagesRoute
  AppMediaRoute: typeof AppMediaRoute
  AppPlannerRoute: typeof AppPlannerRoute
  AppPostsRoute: typeof AppPostsRouteWithChildren
  AppRecommendationsRoute: typeof AppRecommendationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppIndexRoute: typeof AppIndexRoute
  AppContentTypeRoute: typeof AppContentTypeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBrandRoute: AppBrandRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCampaignsRoute: AppCampaignsRouteWithChildren,
  AppChannelsRoute: AppChannelsRoute,
  AppIdeasRoute: AppIdeasRoute,
  AppImagesRoute: AppImagesRoute,
  AppMediaRoute: AppMediaRoute,
  AppPlannerRoute: AppPlannerRoute,
  AppPostsRoute: AppPostsRouteWithChildren,
  AppRecommendationsRoute: AppRecommendationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppIndexRoute: AppIndexRoute,
  AppContentTypeRoute: AppContentTypeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiMediaRouteChildren {
  ApiMediaIdRoute: typeof ApiMediaIdRoute
}

const ApiMediaRouteChildren: ApiMediaRouteChildren = {
  ApiMediaIdRoute: ApiMediaIdRoute,
}

const ApiMediaRouteWithChildren = ApiMediaRoute._addFileChildren(
  ApiMediaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiMediaRoute: ApiMediaRouteWithChildren,
  ApiChannelsOauthCallbackRoute: ApiChannelsOauthCallbackRoute,
  ApiChannelsOauthProviderRoute: ApiChannelsOauthProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
